version: '3.8'

services:
  speedtest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Backend API (also serves frontend)
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - app_logs:/app/logs

volumes:
  app_logs: