name = "speed-test-app"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "project/dist"
pages_functions_dir = "functions"

[env.production]
name = "speed-test-app"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
RATE_LIMIT_WINDOW_MS = "60000"
RATE_LIMIT_MAX_REQUESTS = "500"

[env.preview]
name = "speed-test-app-preview"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
RATE_LIMIT_WINDOW_MS = "60000"
RATE_LIMIT_MAX_REQUESTS = "500"

# Default environment variables
[vars]
NODE_ENV = "development"
RATE_LIMIT_WINDOW_MS = "60000"
RATE_LIMIT_MAX_REQUESTS = "500"